language: php

php: 
  - 5.3.2
  - 5.3
  - 5.4

branches:
  only:
    - master
    - develop

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: bin/behat -fprogress --tags ~@php540
